### ISSUE TITLE
[BadgerDB] panic: Only one iterator can be active at one time

### ISSUE THREAD

**Issue by bt** [alash3al/bbadger#1]
Hey there,

I've been adapting your fork to a database I'm making for work but it seems that a recent commit to BadgerDB is causing a panic on the Blevesearch tests.

Specifically, it's this commit https://github.com/dgraph-io/badger/commit/b1ad1e93e483bbfef123793ceedc9a7e34b09f79

in the `TestReaderIsolation` test, it fails with the panic:

```
panic: Only one iterator can be active at one time. [recovered]
	panic: Only one iterator can be active at one time.
```

This is because BadgerDB now panics if there are multiple iterators in a single transaction.

**Comment by alash3al** [comment]
Hi @bt, I'm sorry because I wasn't available at the time of your issue.
Today I've refactored and fixed the package as possible as I can, as well as making all test cases to be ok.

If you are available, just test it and give me your feedback.
